export const GET_PAYMENTS_INIT = "GET_PAYMENTS_INIT";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";

export const GET_PAYMENT_DETAILS_INIT = "GET_PAYMENT_DETAILS_INIT";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";

export const GET_DEBITS_INIT = "GET_DEBITS_INIT";
export const GET_DEBITS_SUCCESS = "GET_DEBITS_SUCCESS";

export const GET_DEBIT_DETAILS_INIT = "GET_DEBIT_DETAILS_INIT";
export const GET_DEBIT_DETAILS_SUCCESS = "GET_DEBIT_DETAILS_SUCCESS";

export const CREATE_PAYMENT_INIT = "CREATE_PAYMENT_INIT";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";

export const CREATE_DEBIT_INIT = "CREATE_DEBIT_INIT";
export const CREATE_DEBIT_SUCCESS = "CREATE_DEBIT_SUCCESS";

export const API_ERROR = "PAYMENTS_API_ERROR";
