export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_INIT = "REGISTER_INIT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const GOOGLE_REGISTER_SUCCESS = "GOOGLE_REGISTER_SUCCESS";
export const GOOGLE_REGISTER_FAIL = "GOOGLE_REGISTER_FAIL";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const GET_RECEIVER_INFO = "GET_RECEIVER_INFO";
export const GET_RECEIVER_INFO_ERROR = "GET_RECEIVER_INFO_ERROR";

export const USER_ERROR = "USER_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

export const SET_SKELETON = "SET_SKELETON";
export const REMOVE_SKELETON = "REMOVE_SKELETON";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const API_ERROR = "LOGIN_API_ERROR";

export const RESET_PENDING = "RESET_PENDING";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAIL = "RESET_FAIL";

export const PASS_RESET_SUCCESS = "PASS_RESET_SUCCESS";
export const PASS_RESET_FAIL = "PASS_RESET_FAIL";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_BANK_INIT = "GET_BANK_INIT";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";
export const GET_BANKS_ERROR = "GET_BANKS_ERROR";

export const GET_CURRENCIES_INIT = "GET_CURRENCIES_INIT";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_ERROR = "GET_CURRENCIES_ERROR";

export const TRANSACTIONS_LOADED = "TRANSACTIONS_LOADED";
export const TRANSACTIONS_ERROR = "TRANSACTIONS_ERROR";

export const PAYMENTS_LOADED = "PAYMENTS_LOADED";
export const PAYMENTS_ERROR = "PAYMENTS_ERROR";

export const DEBITS_LOADED = "DEBITS_LOADED";
export const DEBITS_ERROR = "DEBITS_ERROR";

export const GET_DEBIT_LOADED = "GET_DEBIT_LOADED";
export const GET_DEBIT_ERROR = "GET_DEBIT_ERROR";

export const GET_PAYMENT_LOADED = "GET_PAYMENT_LOADED";
export const GET_PAYMENT_ERROR = "GET_PAYMENT_ERROR";

export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const ACCOUNTS_PENDING = "ACCOUNTS_PENDING";
export const ACCOUNTS_LOADED = "ACCOUNTS_LOADED";
export const ACCOUNTS_ERROR = "ACCOUNTS_ERROR";

export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const GET_ACCOUNT_INFO_ERROR = "GET_ACCOUNT_INFO_ERROR";

export const CATEGORIES_LOADED = "CATEGORIES_LOADED";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const GET_SUPPLIERS_INIT = "GET_SUPPLIERS_INIT";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_ERROR = "GET_SUPPLIERS_ERROR";

export const SUPPLIERS_LOADED = "SUPPLIERS_LOADED";
export const SUPPLIERS_ERROR = "SUPPLIERS_ERROR";

export const SUPPLIER_PROFILE_LOADED = "SUPPLIER_PROFILE_LOADED";
export const SUPPLIER_PROFILE_ERROR = "SUPPLIER_PROFILE_ERROR";

export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const PRODUCT_INFO_LOADED = "PRODUCT_INFO_LOADED";
export const PRODUCT_INFO_ERROR = "PRODUCT_INFO_ERROR";

export const CREATE_ACCOUNT_PENDING = "CREATE_ACCOUNT_PENDING";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const UPDATE_PROFILE_PENDING = "UPDATE_PROFILE_PENDING";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const SEND_TRANSACTION_PENDING = "SEND_TRANSACTION_PENDING";
export const SEND_REQUEST_SUCCESS = "SEND_REQUEST_SUCCESS";
export const SEND_TRANSACTION_SUCCESS = "SEND_TRANSACTION_SUCCESS";
export const SEND_TRANSACTION_FAIL = "SEND_TRANSACTION_FAIL";

export const SEND_DEBIT = "SEND_DEBIT";
export const SEND_DEBIT_SUCCESS = "SEND_DEBIT_SUCCESS";
export const SEND_DEBIT_FAIL = "SEND_DEBIT_FAIL";

export const SEND_DETAIL_SUCCESS = "SEND_DETAIL_SUCCESS";
export const SEND_DETAIL_FAIL = "SEND_DETAIL_FAIL";

export const CC_PAYMENT_PENDING = "CC_PAYMENT_PENDING";
export const CC_PAYMENT_SUCCESS = "CC_PAYMENT_SUCCESS";
export const CC_PAYMENT_FAIL = "CC_PAYMENT_FAIL";

export const CREATE_PAYMENT_INIT = "CREATE_PAYMENT_INIT";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";
