export const GET_ACCOUNTS_INIT = "GET_ACCOUNTS_INIT";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";

export const GET_ACCOUNT_INFO_INIT = "GET_ACCOUNT_INFO_INIT";
export const GET_ACCOUNT_INFO_SUCCESS = "GET_ACCOUNT_INFO_SUCCESS";

export const ADD_ACCOUNT_INIT = "ADD_ACCOUNT_INIT";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";

export const API_ERROR = "ACCOUNTS_API_ERROR";
