export const GET_BANKS_INIT = "GET_BANKS_INIT";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";

export const GET_CURRENCIES_INIT = "GET_CURRENCIES_INIT";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";

export const API_ERROR = "BANKS_API_ERROR";
