export const LOAD_USER_INIT = "LOAD_USER_INIT";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const START_REGISTRATION_INIT = "START_REGISTRATION_INIT";
export const START_REGISTRATION_SUCCESS = "START_REGISTRATION_SUCCESS";

export const COMPLETE_REGISTRATION_INIT = "COMPLETE_REGISTRATION_INIT";
export const COMPLETE_REGISTRATION_SUCCESS = "COMPLETE_REGISTRATION_SUCCESS";

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const SEND_PASS_RESET_INIT = "SEND_PASS_RESET_INIT";
export const SEND_PASS_RESET_SUCCESS = "SEND_PASS_RESET_SUCCESS";

export const CHECK_PASS_RESET_TOKEN = "CHECK_PASS_RESET_TOKEN";
export const CHECK_PASS_RESET_TOKEN_SUCCESS = "CHECK_PASS_RESET_TOKEN_SUCCESS";

export const PASSWORD_RESET_INIT = "PASSWORD_RESET_INIT";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";

export const UPDATE_PROFILE_INIT = "UPDATE_PROFILE_INIT";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const API_ERROR = "AUTH_API_ERROR";
export const CLEAR_ERROR = "CLEAR_AUTH_ERROR";
