export const GET_SUPPLIERS_INIT = "GET_SUPPLIERS_INIT";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";

export const GET_SUPPLIER_INFO_INIT = "GET_SUPPLIER_INFO_INIT";
export const GET_SUPPLIER_INFO_SUCCESS = "GET_SUPPLIER_INFO_SUCCESS";

export const GET_PRODUCTS_INIT = "GET_PRODUCTS_INIT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCT_INFO_INIT = "GET_PRODUCT_INFO_INIT";
export const GET_PRODUCT_INFO_SUCCESS = "GET_PRODUCT_INFO_SUCCESS";

export const SET_LOADING = "SET_SUPPLIER_LOADING";
export const REMOVE_LOADING = "REMOVE_SUPPLIER_LOADING";

export const API_ERROR = "SUPPLIER_ERROR";
